### ISSUE TITLE
Can I buy you beer for this guide?

### ISSUE THREAD

**Issue by dmitriz** [sindresorhus/guides#31]
It really changed my life!

**Comment by sindresorhus** [comment]
Glad you found it useful. I don't drink :beer:, but thanks for the offer ;)

**Comment by dmitriz** [comment]
I kind of thought... good decision!

Yes, it was insanely helpful to solve the silly problem people have been having for years....

These guides can be life saver, given how terse the officials docs are, for instance, I couldn't believe I would keep hitting my head against the wall for [this kind of problem](http://stackoverflow.com/questions/34781630/how-to-copy-files-from-package-to-local-directory-after-npm-installation) but sadly I still cannot do it. :(
