### ISSUE TITLE
Question about rm -fr

### ISSUE THREAD

**Issue by ioab** [sindresorhus/guides#37]
Hi, and thanks for the great collection.

I was wondering if there's a safety option against using 'rm -fr' ?
It seems that bash steps mentioned in "How not to rm yourself", and 'rm -i' is bypassed with this command.

**Comment by sindresorhus** [comment]
This is explained this in the guide. There are other things you can do to protect yourself, but in the end, the only real protection is to have a backup. I would recommend using [`trash`](https://github.com/sindresorhus/trash-cli) whenever you can.
