### ISSUE TITLE
Yeoman loading fountain-webapp with errors

### ISSUE THREAD

**Issue by mverdera4** [sindresorhus/guides#39]
![capture](https://cloud.githubusercontent.com/assets/23083513/19739204/a76c3d42-9b7f-11e6-814c-2ed8ece87cd5.JPG)

This is on a windows 7 Enterprise machine. Would this be the problem? I have upgraded NPM.
thanks in advance, trying to make SharePoint webparts.

**Comment by SamVerschueren** [comment]
Node version? My best guess is to upgrade it to 4+.

**Comment by kevva** [comment]
As @SamVerschueren said, you're most likely using an outdated Node.js version. Try upgrading, and if it doesn't work, open an issue at the correct repository.

**Comment by mverdera4** [comment]
my npm version is 2.7.4.

**Comment by mverdera4** [comment]
I do a 'npm upgrade' and the version stays at 2.7.4

**Comment by kevva** [comment]
Node.js and npm are two different things. Go to https://nodejs.org/ (or use `n` or `nvm`) to update Node.js. To update npm you would do `npm install -g npm@latest`.

**Comment by mverdera4** [comment]
It is working now, I did the upgrade directly from the node.js page. I mistakenly thought NPM would upgrade Node.
thanks,
