### ISSUE TITLE
Official documentation

### ISSUE THREAD

**Issue by FDiskas** [sindresorhus/guides#41]
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by sindresorhus** [comment]
?

**Comment by SamVerschueren** [comment]
I think that he means it is now officially documented by npm. But that might have always been the case?

**Comment by FDiskas** [comment]
I tried your script on fedora25 and it stops with some syntax error. So official version worked.

**Comment by heyakyra** [comment]
This worked best for me: http://michaelb.org/the-right-way-to-do-global-npm-install-without-sudo/

**Comment by sindresorhus** [comment]
We are already linking to the npm docs in the guide: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
