### ISSUE TITLE
This is not working on debian 9

### ISSUE THREAD

**Issue by spaceneenja** [sindresorhus/guides#48]
Debian 9.7
Node 6.16.0
NPM 3.10.10

Using the Google Click to Deploy node.js application runtime on compute engine gives us a fresh instance.

As non-root user:
`wget -O- https://raw.githubusercontent.com/glenpike/npm-g_nosudo/master/npm-g-nosudo.sh | sh`
`source ~/.bashrc`
`npm install --global gatsby`
`gatsby --version`

Expected outcome prints gatsby version

Actual result
> -bash: gatsby: command not found

Using the original instructions provided here however do work.
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by sindresorhus** [comment]
Open an issue on https://github.com/glenpike/npm-g_nosudo instead.
