### ISSUE TITLE
Required fix on docker-without-sudo

### ISSUE THREAD

**Issue by pintify** [sindresorhus/guides#60]
I'm working with Ubuntu 20 and I required to run also `newgrp docker` prior to see the groups configuration applied.

**Comment by sindresorhus** [comment]
Pull request welcome if someone does a (much!) better job than the previous low-quality pull requests:

- https://github.com/sindresorhus/guides/pull/58
- https://github.com/sindresorhus/guides/pull/59
- https://github.com/sindresorhus/guides/pull/49
- https://github.com/sindresorhus/guides/pull/51
